### PR TITLE
Building on/for macOS arm64

### PR DESCRIPTION
**Pull request by reduzent**
I made a few changes to the Makefile and the localdeps script, so that:
  * the external is using the arch specific extension (.d_arm64)
  * all dependencies are copied to a folder named after the current arch
  * the external and dependencies get a codesign refresh

This is how I build on Monterey:

```
make CPPFLAGS+=-I/opt/homebrew/include LDFLAGS+=-L/opt/homebrew/lib extension=d_arm64 PDDIR=(path_to_pd) PDLIBDIR=(path_to_externals) localdep_macos
```

### CODE REVIEW

**Comment by porres** [comment]
> This is how I build on Monterey:

I get this when I try to build it this way

-bash: syntax error near unexpected token `('

**Comment by porres** [comment]
tried on mojave by the way... do I need to have fluidsynth installed on the machine I'm building? or does it get from 'homebrew' or something?

**Comment by porres** [comment]
> I get this when I try to build it this way

on monterey (intel) I get 

zsh: number expected

**Comment by porres** [comment]
> This is how I build on Monterey:

On monterey (intel) I get: **zsh: number expected**

**Comment by reduzent** [comment]
Yeah, sorry, I shouldn't have put parentheses there. I thought I'd use them to make clear, that the stuff after `=` should be replaced with what works for you. Here is the exact command that works for me on Monterey:

```
make CPPFLAGS+=-I/opt/homebrew/include LDFLAGS+=-L/opt/homebrew/lib extension=d_arm64 PDDIR=/Users/roman/pd-src/pure-data/ PDLIBDIR=/Users/roman/Pd/externals/ localdep_macos
```

**Comment by reduzent** [comment]
And yes, I did install fluidsynth with homebrew before building:

```
brew install fluid-synth
```

**Comment by porres** [comment]
awesome, thanks, I'm working a lot on the object and discovering amazinh things like its built in effects and microtonal capabilities!

**Pull request merged**
